name: Update profile stats

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - ".github/workflows/profile-stats.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate profile metrics
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics.svg
          token: ${{ secrets.STREAK_STATS_TOKEN }}
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Africa/Accra
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_followup: yes
          plugin_followup_sections: repositories

      - name: Commit profile stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/metrics.svg
          git commit -m "Update profile metrics" || exit 0
          git push
